"""Render documentation templates whose numbers come only from results/*.json.

Template syntax (inside any *.tmpl file under docs/templates/, README.md.tmpl, writeup/*.tmpl):

    {{ trajectory_cv.json : by_k.3.curve_mae.mean.neurotrajectory | .3f }}
    {{ epa_baseline_repro.json : models.DIV12.balanced_accuracy_pct | .1f }}
    {{ data_audit_brewer.json : n_axons }}                 (no format -> str())
    {{ trajectory_cv.json : by_k.3.curve_mae.paired_vs_best.rel_change_pct | abs .1f }}

Path components index dicts by key and lists by integer. Formats: any Python format spec,
optionally prefixed by 'abs', 'pct' (x100) or 'neg'. Output: the rendered file next to the
template target (docs/templates/X.md.tmpl -> docs/X.md; README.md.tmpl -> README.md) and
docs/NUMBERS.md, a ledger of every number with its source, used by scripts/check_numbers.py.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
RESULTS = REPO / "results"
PAT = re.compile(r"\{\{\s*([\w./-]+\.json)\s*:\s*([\w.\-]+)\s*(?:\|\s*([^}]*?))?\s*\}\}")


def lookup(obj, path):
    for part in path.split("."):
        if isinstance(obj, list):
            obj = obj[int(part)]
        else:
            if part not in obj:
                raise KeyError(f"missing key '{part}' in path '{path}'")
            obj = obj[part]
    return obj


def fmt(val, spec):
    if not spec:
        return str(val)
    spec = spec.strip()
    for mod in ("abs", "pct", "neg"):
        if spec.startswith(mod):
            spec = spec[len(mod):].strip()
            val = abs(val) if mod == "abs" else (100 * val if mod == "pct" else -val)
    return format(val, spec) if spec else str(val)


def targets():
    pairs = []
    for t in sorted((REPO / "docs/templates").glob("*.tmpl")):
        pairs.append((t, REPO / "docs" / t.name[:-5]))
    for t in sorted(REPO.glob("*.tmpl")):
        pairs.append((t, REPO / t.name[:-5]))
    for t in sorted((REPO / "writeup").glob("*.tmpl")) if (REPO / "writeup").exists() else []:
        pairs.append((t, REPO / "writeup" / t.name[:-5]))
    return pairs


def main():
    cache, ledger, errors = {}, [], []
    for src, dst in targets():
        text = src.read_text(encoding="utf-8")

        def repl(m):
            fname, path, spec = m.group(1), m.group(2), m.group(3)
            try:
                if fname not in cache:
                    cache[fname] = json.loads((RESULTS / fname).read_text(encoding="utf-8"))
                out = fmt(lookup(cache[fname], path), spec)
            except Exception as e:  # noqa: BLE001
                errors.append(f"{src.name}: {fname}:{path} -> {e}")
                return "??"
            ledger.append((dst.relative_to(REPO).as_posix(), out, f"{fname}:{path}"))
            return out

        dst.write_text(PAT.sub(repl, text), encoding="utf-8")
    rows = ["# Numbers ledger", "",
            "Every number printed in the rendered documents, with the results file it comes from.",
            "Generated by `scripts/render_docs.py`; checked by `scripts/check_numbers.py`.", "",
            "| document | value | source |", "|---|---|---|"]
    rows += [f"| {d} | {v} | `{s}` |" for d, v, s in ledger]
    (REPO / "docs/NUMBERS.md").write_text("\n".join(rows) + "\n", encoding="utf-8")
    (RESULTS / "numbers_ledger.json").write_text(json.dumps(
        [{"doc": d, "value": v, "source": s} for d, v, s in ledger], indent=1), encoding="utf-8")
    print(f"rendered {len(targets())} documents, {len(ledger)} numbers")
    if errors:
        print("ERRORS:\n  " + "\n  ".join(errors))
        sys.exit(1)


if __name__ == "__main__":
    main()
