"""Render documentation templates whose numbers come only from results/*.json.

Template syntax (inside any *.tmpl file under docs/templates/, README.md.tmpl, writeup/*.tmpl):

    {{ trajectory_cv.json : by_k.3.curve_mae.mean.neurotrajectory | .3f }}
    {{ epa_baseline_repro.json : models.DIV12.balanced_accuracy_pct | .1f }}
    {{ data_audit_brewer.json : n_axons }}                 (no format -> str())
    {{ trajectory_cv.json : by_k.3.curve_mae.paired_vs_best.rel_change_pct | abs .1f }}

Path components index dicts by key and lists by integer. A key that itself contains dots
(e.g. 'alpha_0.1' in conformal_r7.json, 'AUC.3hit' in dnt_r4.json) is written as is: when a
component is missing, the next components are joined with '.' until a key matches. Keys may
also contain '=' (e.g. 'B=3' in r6_dosecompass.json). Formats: any Python format spec,
optionally prefixed by 'abs', 'pct' (x100) or 'neg'. Output: the rendered file next to the
template target (docs/templates/X.md.tmpl -> docs/X.md; README.md.tmpl -> README.md;
report/X.tex.tmpl -> report/X.tex; report/figures/captions.md -> captions_rendered.md) and
docs/NUMBERS.md, a ledger of every number with its source, used by scripts/check_numbers.py.
The report PDF is then built by scripts/build_report.py.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
RESULTS = REPO / "results"
PAT = re.compile(r"\{\{\s*([\w./-]+\.json)\s*:\s*([\w.\-=]+)\s*(?:\|\s*([^}]*?))?\s*\}\}")


def lookup(obj, path):
    parts = path.split(".")
    i = 0
    while i < len(parts):
        part = parts[i]
        if isinstance(obj, list):
            obj = obj[int(part)]
            i += 1
            continue
        j = i
        while part not in obj and j + 1 < len(parts):     # key containing dots, e.g. 'alpha_0.1'
            j += 1
            part = part + "." + parts[j]
        if part not in obj:
            raise KeyError(f"missing key '{parts[i]}' in path '{path}'")
        obj = obj[part]
        i = j + 1
    return obj


def fmt(val, spec):
    if not spec:
        return str(val)
    spec = spec.strip()
    for mod in ("abs", "pct", "neg"):
        if spec.startswith(mod):
            spec = spec[len(mod):].strip()
            val = abs(val) if mod == "abs" else (100 * val if mod == "pct" else -val)
    return format(val, spec) if spec else str(val)


def targets():
    pairs = []
    for t in sorted((REPO / "docs/templates").glob("*.tmpl")):
        pairs.append((t, REPO / "docs" / t.name[:-5]))
    for t in sorted(REPO.glob("*.tmpl")):
        pairs.append((t, REPO / t.name[:-5]))
    for t in sorted((REPO / "writeup").glob("*.tmpl")) if (REPO / "writeup").exists() else []:
        pairs.append((t, REPO / "writeup" / t.name[:-5]))
    for t in sorted((REPO / "report").glob("*.tmpl")) if (REPO / "report").exists() else []:
        pairs.append((t, REPO / "report" / t.name[:-5]))
    caps = REPO / "report/figures/captions.md"         # figure captions (also rendered by make_figures.py)
    if caps.exists():
        pairs.append((caps, caps.with_name("captions_rendered.md")))
    return pairs


def main():
    cache, ledger, errors = {}, [], []
    for src, dst in targets():
        text = src.read_text(encoding="utf-8")

        def repl(m):
            fname, path, spec = m.group(1), m.group(2), m.group(3)
            try:
                if fname not in cache:
                    cache[fname] = json.loads((RESULTS / fname).read_text(encoding="utf-8"))
                out = fmt(lookup(cache[fname], path), spec)
            except Exception as e:  # noqa: BLE001
                errors.append(f"{src.name}: {fname}:{path} -> {e}")
                return "??"
            ledger.append((dst.relative_to(REPO).as_posix(), out, f"{fname}:{path}"))
            return out

        dst.write_text(PAT.sub(repl, text), encoding="utf-8", newline="\n")   # LF on every OS
    rows = ["# Numbers ledger", "",
            "Every number printed in the rendered documents, with the results file it comes from.",
            "Generated by `scripts/render_docs.py`; checked by `scripts/check_numbers.py`.", "",
            "| document | value | source |", "|---|---|---|"]
    rows += [f"| {d} | {v} | `{s}` |" for d, v, s in ledger]
    (REPO / "docs/NUMBERS.md").write_text("\n".join(rows) + "\n", encoding="utf-8", newline="\n")
    (RESULTS / "numbers_ledger.json").write_text(json.dumps(
        [{"doc": d, "value": v, "source": s} for d, v, s in ledger], indent=1), encoding="utf-8", newline="\n")
    print(f"rendered {len(targets())} documents, {len(ledger)} numbers")
    if errors:
        print("ERRORS:\n  " + "\n  ".join(errors))
        sys.exit(1)


if __name__ == "__main__":
    main()
